// Regenerates src/lib/tap-abi.ts from the Foundry build output.
// Run `forge build` in ../contracts first, then `pnpm abi`.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const artifact = JSON.parse(readFileSync(`${root}../contracts/out/Tap.sol/Tap.json`, "utf8"));

const body = `// Generated by scripts/gen-abi.mjs from contracts/out/Tap.sol/Tap.json. Do not edit.
export const tapAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
writeFileSync(`${root}src/lib/tap-abi.ts`, body);
console.log(`Wrote ${artifact.abi.length} ABI entries to src/lib/tap-abi.ts`);
